### ISSUE TITLE
I thought something else 

### ISSUE THREAD

**Issue by atsuyim** [stamparm/DSSS#6]
well i though the whole point of scanning the site was to find the vulnerability.
but in your example you have it something like this 

dsss.py -u "http://www.dsss.net/id=1"

LOL and what if i don't want to search it manually?
what if i simply add something like this

dsss.py -u "http://www.dsss.net"

NOTHING HAPPENS

**Comment by stamparm** [comment]
DSSS doesn't support crawling nor form searching. It only supports SQLi search per provided link (e.g. with GET parameters)

You can find all such potential links with some other tool (e.g. Burp)

LOL
